export const SET_LOADING = 'SET_LOADING';
export const GET_TODO_ITEMS_SUCCESS = 'GET_TODO_ITEMS_SUCCESS';
export const GET_TODO_ITEMS_ERROR = 'GET_TODO_ITEMS_ERROR';
export const CREATE_TODO_ITEM_SUCCESS = 'CREATE_TODO_ITEM';
export const CREATE_TODO_ITEM_ERROR = 'CREATE_TODO_ITEM_ERROR';
export const EDIT_TODO_ITEM_SUCCESS = 'EDIT_TODO_ITEM_SUCCESS';
export const EDIT_TODO_ITEM_ERROR = 'EDIT_TODO_ITEM_ERROR';
export const DELETE_TODO_ITEM_SUCCESS = 'DELETE_TODO_ITEM_SUCCESS';
export const DELETE_TODO_ITEM_ERROR = 'DELETE_TODO_ITEM_ERROR';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const ADD_TODO_ACTION = 'ADD_TODO_ACTION';
export const DELETE_TODO_ACTION = 'DELETE_TODO_ACTION';
export const EDIT_TODO_ACTION = 'EDIT_TODO_ACTION';
